#!/usr/bin/env python3

import re
from pathlib import Path


root = Path(__file__).resolve().parent.parent

FILE = root / "gen/__init__.py"

if not FILE.exists():
    raise SystemExit("__init__ file not found")

text = FILE.read_text()

m = re.search(r"\d+\.\d+\.\d+", text)
if not m:
    print(text)
    print(m)
    raise SystemExit("Version not found")

# Update like abacus
major, minor, patch = map(int, m.group(0).split("."))

patch += 1
if patch >= 100:
    patch = 0
    minor += 1

if minor >= 100:
    minor = 0
    major += 1

new_version = f"{major}.{minor}.{patch}"

new_text = f"""
__VERSION__ = "{new_version}"

# note this is auto generated by pre commit hook.
"""

FILE.write_text(new_text)

print("Version bump:", new_version)