// Auto-generated by scripts/update-site-projects.py — do not edit.

export type RepoEntry = {
  repo: string;
  url: string;
  description: string;
  ollama_description: string;
  keywords: string[];
  stack: string[];
  types: string[];
  pushedAt: string;
  stars: number;
  primaryLanguage: string | null;
};

export const repositories: RepoEntry[] = [
  {
    "repo": "PIIPAYA",
    "url": "https://github.com/jayf0x/PIIPAYA",
    "description": "Local macOS app that anonymizes sensitive documents while keeping the narrative intact. Replaces names, dates, emails and other PII with consistent pseudonyms using a deterministic seeding layer on top of Microsoft Presidio, so anonymized text stays coherent for LLM analysis or human review.  Topics",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-04-28T08:17:31Z",
    "stars": 0,
    "primaryLanguage": "Svelte"
  },
  {
    "repo": "majic",
    "url": "https://github.com/jayf0x/majic",
    "description": "Right-click front-end for personal scripts. Macos Util.",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-04-29T15:27:00Z",
    "stars": 0,
    "primaryLanguage": "Swift"
  },
  {
    "repo": "react-trace-visual",
    "url": "https://github.com/jayf0x/react-trace-visual",
    "description": "Educational visualization of the React ecosystem",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-04-29T13:25:02Z",
    "stars": 0,
    "primaryLanguage": "TypeScript"
  },
  {
    "repo": "Pure-Paste",
    "url": "https://github.com/jayf0x/Pure-Paste",
    "description": "macOS menu-bar app that strips tracking parameters (utm_*, fbclid, etc.) from any         copied URL. Uses merged rules from uBlock Origin and ClearURLs. Fully local and private.",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-04-22T08:27:45Z",
    "stars": 0,
    "primaryLanguage": "Swift"
  },
  {
    "repo": "audio-bonanza",
    "url": "https://github.com/jayf0x/audio-bonanza",
    "description": "Chrome extension for per-tab audio control (speed, reverb, bass..) focused on YouTube,         with optional Flask SSE backend for LAN-wide remote triggering from any device. Free & local",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-04-27T15:59:04Z",
    "stars": 0,
    "primaryLanguage": "JavaScript"
  },
  {
    "repo": "cli-utils",
    "url": "https://github.com/jayf0x/cli-utils",
    "description": "cli-utils",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-04-27T15:59:18Z",
    "stars": 0,
    "primaryLanguage": "Python"
  },
  {
    "repo": "js-canvas",
    "url": "https://github.com/jayf0x/js-canvas",
    "description": "My first digital art with js canvas. Includes unfinished projects",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-04-22T07:40:40Z",
    "stars": 0,
    "primaryLanguage": "JavaScript"
  },
  {
    "repo": "doubledash-css-var-editor",
    "url": "https://github.com/jayf0x/doubledash-css-var-editor",
    "description": "Chrome DevTools sidebar with fuzzy-search and live edit CSS vars with better workflow than native browser tooling",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-04-20T19:31:12Z",
    "stars": 0,
    "primaryLanguage": "JavaScript"
  },
  {
    "repo": "Aqtive",
    "url": "https://github.com/jayf0x/Aqtive",
    "description": "Keeps your mac awake while Claude is running or you simply want your screen to remain active while giving a presentation",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-04-16T20:23:07Z",
    "stars": 0,
    "primaryLanguage": "Python"
  },
  {
    "repo": "fluidity",
    "url": "https://github.com/jayf0x/fluidity",
    "description": "WebGL fluid simulation for React — text & image effects",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-04-20T14:41:25Z",
    "stars": 0,
    "primaryLanguage": "TypeScript"
  },
  {
    "repo": "ideaditor",
    "url": "https://github.com/jayf0x/ideaditor",
    "description": "Lightweight Markdown knowledge base bundled with Tauri, Bun for faster ideation compatible with Obsidian",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-03-18T19:45:40Z",
    "stars": 0,
    "primaryLanguage": "TypeScript"
  },
  {
    "repo": "L.E.M.O.N.",
    "url": "https://github.com/jayf0x/L.E.M.O.N.",
    "description": "research into using nature as a guide for aligned intelligence infrastructure",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-03-18T16:29:44Z",
    "stars": 0,
    "primaryLanguage": "Shell"
  },
  {
    "repo": "yin-yang-rotation",
    "url": "https://github.com/jayf0x/yin-yang-rotation",
    "description": "fun yinyang rotation",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-02-03T11:09:25Z",
    "stars": 0,
    "primaryLanguage": "JavaScript"
  },
  {
    "repo": "voice-of-markdown",
    "url": "https://github.com/jayf0x/voice-of-markdown",
    "description": "create markdown with voice control",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-02-24T22:15:22Z",
    "stars": 0,
    "primaryLanguage": "Python"
  },
  {
    "repo": "sha256-remake",
    "url": "https://github.com/jayf0x/sha256-remake",
    "description": "remake of sha256 from shell outputs as exercise",
    "ollama_description": "",
    "keywords": [],
    "stack": [],
    "types": [],
    "pushedAt": "2026-01-05T09:28:20Z",
    "stars": 0,
    "primaryLanguage": "Python"
  }
];
